using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TeddyBearExport.Model
{
    public enum VrstaDrvo
    {
        [Description("Bela vrba")] BelaVrba = 11,
        [Description("Bademasta vrba")] BademastaVrba = 12,
        [Description("Krta vrba")] KrtaVrba = 13,
        [Description("Siva vrba")] SivaVrba = 14,
        [Description("Crna jova")] CrnaJova = 21,
        [Description("Bela jova")] BelaJova = 22,
        [Description("Bela topola")] BelaTopola = 23,
        [Description("Crna topola")] CrnaTopola = 24,
        [Description("Topola roubsta")] TopolaRoubsta = 25,
        [Description("Topola serotina")] TopolaSerotina = 26,
        [Description("Topola marilandika")] TopolaMarilandika = 27,
        [Description("Topola ostia")] TopolaOstia = 28,
        [Description("Topola I-154")] TopolaI154 = 29,
        [Description("Topola I-214")] TopolaI214 = 30,
        [Description("Deltoidna topola")] DeltoidnaTopola = 31,
        [Description("Siva topola")] SivaTopola = 32,
        [Description("Topola M1")] TopolaM1 = 33,
        [Description("Sibirski brest")] SibirskiBrest = 34,
        [Description("Domaći orah")] DomaciOrah = 37,
        [Description("Poljski brest")] PoljskiBrest = 38,
        [Description("Vez")] Vez = 39,
        [Description("Ostali meki lišćari")] OstaliMekiLiscari = 40,
        [Description("Poljski jasen")] PoljskiJasen = 41,
        [Description("Lužnjak")] Luznjak = 42,
        [Description("Grab")] Grab = 43,
        [Description("Cer")] Cer = 44,
        [Description("Sitnolisna lipa")] SitnolisnaLipa = 45,
        [Description("Krupnolisna lipa")] KrupnolisnaLipa = 46,
        [Description("Srebrna lipa")] SrebrnaLipa = 47,
        [Description("Koprivić")] Koprivic = 48,
        [Description("Sladun")] Sladun = 49,
        [Description("Trešnja")] Tresnja = 50,
        [Description("Ostali tvrdi lišćari")] OstaliTvrdiLiscari = 51,
        [Description("Kesten")] Kesten = 52,
        [Description("Medunac")] Medunac = 53,
        [Description("Crni jasen")] CrniJasen = 54,
        [Description("Grabić")] Grabic = 55,
        [Description("Crni grab")] CrniGrab = 56,
        [Description("Kitnjak")] Kitnjak = 57,
        [Description("Jasika")] Jasika = 58,
        [Description("Breza")] Breza = 59,
        [Description("Mečja leska")] MecjaLeska = 60,
        [Description("Bukva")] Bukva = 61,
        [Description("Planinski brest")] PlaninskiBrest = 62,
        [Description("Beli jasen")] BeliJasen = 63,
        [Description("Mleč")] Mlec = 64,
        [Description("Javor")] Javor = 65,
        [Description("Planinski javor")] PlaninskiJavor = 66,
        [Description("Jela")] Jela = 67,
        [Description("Smrča")] Smrca = 68,
        [Description("Omorika")] Omorika = 69,
        [Description("Crni bor")] CrniBor = 70,
        [Description("Beli bor")] BeliBor = 71,
        [Description("Molika")] Molika = 72,
        [Description("Munika")] Munika = 73,
        [Description("Krivulj")] Krivulj = 74,
        [Description("Bagrem")] Bagrem = 75,
        [Description("Crni orah")] CrniOrah = 76,
        [Description("Američki jasen")] AmerickiJasen = 77,
        [Description("Gledicija")] Gledicija = 78,
        [Description("Crveni hrast")] CrveniHrast = 79,
        [Description("Platan")] Platan = 80,
        [Description("Kiselo drvo")] KiseloDrvo = 81,
        [Description("Jasenoliki javor")] JasenolikiJavor = 82,
        [Description("Duglazija")] Duglazija = 83,
        [Description("Borovac")] Borovac = 84,
        [Description("Grandisova jela")] GrandisovaJela = 85,
        [Description("Normandiana")] Normandiana = 86,
        [Description("Ariš")] Aris = 87,
        [Description("Džefrej")] Dzefrej = 88,
        [Description("Ponderoza")] Ponderoza = 89,
        [Description("Kedar")] Kedar = 90,
        [Description("Tisa")] Tisa = 91,
        [Description("Katalpa")] Katalpa = 92,
        [Description("Ostali četinari")] OstaliCetinari = 93,
        [Description("Jarebika")] Jarebika = 94,
        [Description("Klen")] Klen = 95,
        [Description("Sofora")] Sofora = 96,
        [Description("Makedonski hrast")] MakedonskiHrast = 97,
        [Description("Virdžinijska borov. kleka")] VirdzinijskaBorovKleka = 98,
        [Description("Brekinja")] Brekinja = 99
    }
}
