    <Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	<PlatformTarget>x86</PlatformTarget>
	<ApplicationIcon>teddy.ico</ApplicationIcon>
	<NoWarn>NU1605</NoWarn>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="PdfUtils\doznaka_template.html" />
  </ItemGroup>

    <ItemGroup>
	    <Content Include="PdfUtils\doznaka_template.html">
	      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	    </Content>
	    <Content Include="PdfUtils\template.html" CopyToOutputDirectory="PreserveNewest" />
	    <Resource Include="teddy.ico" />
    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="LibWkHtmlToX-32" Version="0.12.6.1" />
    <PackageReference Include="System.Data.OleDb" Version="9.0.10" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="teddy.jpg" />
  </ItemGroup>

</Project>
